Support Unreal Engine 5.5
colory-games/UEPlugin-AccessVariableByName pull request #53
Opened 2024-11-27 19:03 UTC by pdxmholmes

Make the small set of changes needed to support Unreal 5.5.

2024-12-08 11:36 UTC, nutti requested changes
Thank you @pdxmholmes !

We are now confirming this patch works fine.
I request a small change.

2024-12-08 11:36 UTC, nutti commented on tools/replace_engine_version.sh
Below code needs to be changed.

```
for file in `find ${source_dir} -name "*.uplugin"`; do
    sed -i -e "s/\"EngineVersion\": \"5.4.0\",/\"EngineVersion\": \"${engine_version}\",/g" ${file}
    echo "Replaced engine version in ${file}"
done
```

2024-12-11 22:17 UTC, pdxmholmes commented on tools/replace_engine_version.sh
I'll take care of this tonight.

2024-12-23 06:09 UTC, closed without merging

2024-12-23 06:13 UTC, nutti commented
@pdxmholmes 

Sorry, I deleted the commits by mistake.
Could you apply these changes to your main branch?

https://github.com/colory-games/UEPlugin-AccessVariableByName/tree/pdxmholmes-pr-fix

2024-12-27 05:12 UTC, nutti commented
This PR is now merged by https://github.com/colory-games/UEPlugin-AccessVariableByName/commit/bf5e641eb0529156560dbb5421ee1f442be6a6e9 which includes CI fixes.
Thank you @pdxmholmes for your contribution!

2025-01-05 19:33 UTC, pdxmholmes commented
> @pdxmholmes
> 
> Sorry, I deleted the commits by mistake. Could you apply these changes to your main branch?
> 
> https://github.com/colory-games/UEPlugin-AccessVariableByName/tree/pdxmholmes-pr-fix

Sorry I missed this, was away for the Christmas holidays. Seems like you got it working and merged!

2025-01-06 11:38 UTC, nutti commented
@pdxmholmes 

No prob. Thank you for your contribution!